# This file was generated by GoReleaser. DO NOT EDIT.
cask "hauler-dev" do
  version "2.2.0-dev.3"

  on_macos do
    on_arm do
      sha256 "8c4795d2aac0e5ee2f654dee2641c115fcfb88aa52cf34d981f67a9aa14e3042"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "58d17c5ec009f8e93fb5b96e36aab6f57629aa7fb27f609d6959768ae6e36a43"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ef72afefa96ef4bd17926550018b4553ebb97d57406a7aca3ea53a0aeaa02efa"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f1ff0549bc416a8d085f7efc9cd4fe8390e1aee0cd7f76c5e146d8da074c8ad"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hauler-dev"
  desc "Hauler: Airgap Swiss Army Knife (release candidates and dev builds)"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "hauler",
    ]

  binary "hauler"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hauler"]
    end
  end

  # No zap stanza required
end
