# This file was generated by GoReleaser. DO NOT EDIT.
cask "hauler@2.1.2-rc.1" do
  version "2.1.2-rc.1"

  on_macos do
    on_arm do
      sha256 "a790b56b69276e1b46a0e9a671a80c92fe6090b36d540ce3434700bd15e62604"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d13150521a89de9299b27317129b7925e09c2c52ed5a64bb9fe5d7cfa0df907b"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "193653f585347ad0fe75505cf1564cfc020fc85a65192e0b77dca2cc0d4912bb"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "062885ca46bb21c85b2e0f3f8e09c03c2b12bb4d9c0a6bad5aefbf2fb6b7fccf"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hauler@2.1.2-rc.1"
  desc "Hauler: Airgap Swiss Army Knife"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "hauler",
      "hauler-dev",
    ]

  binary "hauler"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hauler"]
    end
  end

  # No zap stanza required
end
