# This file was generated by GoReleaser. DO NOT EDIT.
cask "hauler" do
  version "1.4.3-rc.1"

  on_macos do
    on_intel do
      sha256 "bd4eb3055c6d64596dd6fc597d2ce1b2e81d60787dbd03ec3b6f0a368d0f6d98"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b299952305b425b36737ada38db904d27b60fb833dd044be08729a63392d326b"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4e7f13b8b030ca6d66d88884364619d8113e5024a846a83815ed27b8ac2aab6d"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8ecf87234523424b6a39c908595fd3e55accb461cb605f3fbc70103ebd863ed3"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hauler"
  desc "Hauler: Airgap Swiss Army Knife"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hauler"

  # No zap stanza required

end
