# This file was generated by GoReleaser. DO NOT EDIT.
cask "hauler@2.2.0-dev.2" do
  version "2.2.0-dev.2"

  on_macos do
    on_arm do
      sha256 "5e47ebdf4d493afd63f06c121355e420f84554c4dffd6d2ca513a0ac1ae2aa41"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "14455eeebde4c8622faf4607b46b64d82228d8aeb887e1ba8a35e88237d38550"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e6e31d3bd1f2aafdb818d12b1483d25c0025cb4431d3613e0c95ed7c029d282b"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "19c74bca98d0a0662d8e51a5b19f5af87a3df879281f9f59d1288670b4daa4ec"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hauler@2.2.0-dev.2"
  desc "Hauler: Airgap Swiss Army Knife"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "hauler",
      "hauler-dev",
    ]

  binary "hauler"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hauler"]
    end
  end

  # No zap stanza required
end
