# This file was generated by GoReleaser. DO NOT EDIT.
cask "hauler@2.0.0" do
  version "2.0.0"

  on_macos do
    on_arm do
      sha256 "173e158cff561fb6b894a3e0ac19c4aad2d04b6bc9333438e50f2224c9f3515a"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b431a376da7ba66cc59981f7d2ef1a1364c9e3758ab73dc19d31f2a3a283b1d3"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "947848c4b94145f2ea2d804fb5fd3c831abfbb1ac27fc0eee800437cff2954d9"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a5c807133763df6e0b485ec5d1f1a6836235716b01021f14764e8ac1b58dd4dd"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hauler@2.0.0"
  desc "Hauler: Airgap Swiss Army Knife"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "hauler",
      "hauler-dev",
    ]

  binary "hauler"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hauler"]
    end
  end

  # No zap stanza required
end
