# This file was generated by GoReleaser. DO NOT EDIT.
cask "hauler" do
  version "2.0.1"

  on_macos do
    on_intel do
      sha256 "6ab34763ce6f44d25cd20c6e887e1de0fb4fbe55b0d07c5f432d72ac1f500efe"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "40109b014ec6fd28ff8a5d3128faca73220b8f771c7fce626867e769ad4cd2a2"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c8b65ea57f10a03f02104ebbecbf1249c41f499bc85771488824b70f6ccfc76c"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ffe9811bbb77f844200f0644b98a08b65ee2d5ffcc0e2b49b1df31719a0a052f"
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hauler"
  desc "Hauler: Airgap Swiss Army Knife"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hauler"

  # No zap stanza required

end
