# This file was generated by GoReleaser. DO NOT EDIT.
cask "hauler" do
  name "hauler"
  desc "Hauler: Airgap Swiss Army Knife"
  homepage ""
  version "1.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hauler"

  on_macos do
    on_intel do
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_darwin_amd64.tar.gz"
      sha256 "5101c32b1e76b51a873d88261f88b5cb7f1a7bc6acdbded1d1b11ecd51c2495f"
    end
    on_arm do
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_darwin_arm64.tar.gz"
      sha256 "1b95a100445eeb283a8c5fad6e0fdbfe62000074aadecaea8a77201a3f17e542"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_linux_amd64.tar.gz"
      sha256 "8633ae716847ca0fcab0f654b7966457a0a57f0065bde0c3483af27f9b417e77"
    end
    on_arm do
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_linux_arm64.tar.gz"
      sha256 "66be83f73074b73ca5f8bc5d4cb1c83e7bc7be33276e10d045adf470c40aaa33"
    end
  end

  # No zap stanza required
end
