# This file was generated by GoReleaser. DO NOT EDIT.
cask "hauler" do
  name "hauler"
  desc "Hauler: Airgap Swiss Army Knife"
  homepage ""
  version "1.3.0-dev.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hauler"

  on_macos do
    on_intel do
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_darwin_amd64.tar.gz"
      sha256 "666fd0848ff4cda8d8d367c0c10a2e554c82541dca4b82583c26b1ea8f7fb8ae"
    end
    on_arm do
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_darwin_arm64.tar.gz"
      sha256 "3574b9f9e814f6ddeb9667c2402adcb2aaad1afc50882f1f12d10ddaa0253516"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_linux_amd64.tar.gz"
      sha256 "6b10eb4e98a69103e553768bb0d765a927861a495e4087fcfb121b5d8b80523a"
    end
    on_arm do
      url "https://github.com/hauler-dev/hauler/releases/download/v#{version}/hauler_#{version}_linux_arm64.tar.gz"
      sha256 "9890c468897efc85745ca7ed8c7881c3f67d15ad472fbb5d05b685e045f14103"
    end
  end

  # No zap stanza required
end
